### ISSUE TITLE
Soap MTOM: mtomEnabled=true and XSD schemas=... fails [SWS-958]

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-ws#1030]
**[Martin Peterka](https://jira.spring.io/secure/ViewProfile.jspa?name=martin.peterka)** opened **[SWS-958](https://jira.spring.io/browse/SWS-958?redirect=false)** and commented

Setting _mtomEnabled=true_ and _schemas=..._ causes error:

```xml
<bean id="jaxb2Marshaller" class="org.springframework.oxm.jaxb.Jaxb2Marshaller">
           <!-- .... -->
     <property name="schemas" ref="xsdList"/>
     <property name="mtomEnabled" value="true"/>
</bean>
<bean id="xsdList" class="org.springframework.beans.factory.config.ListFactoryBean">
          <!-- ... -->
```

```xml
<xs:element name="content" type="xs:base64Binary">
```

```
[org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-type.3.1.2: Element 'ns2:content' is a simple type, so it must have no element information item [children].]
```

It seems that validation against XSD was done **after** MTOM data replacement.

**Sample project is here:**
https://github.com/mpeterka/spring-ws-mtom
(Error is in `cz.datalite.spring.mtom.client.WebServiceClientTest#testMarshall` call.)

**Expected behaviour is:**
1. Validate XML message according to XSD.
2. Replace content of data element with MTOM include tag.
3. Send SOAP message.

Disabling message validation is only known workaround.

---

**Affects:** 2.3.0

**Reference URL:** https://github.com/mpeterka/spring-ws-mtom

2 votes, 5 watchers

**Comment by mpeterka** [comment]
A have updated referenced test project: https://github.com/mpeterka/spring-ws-mtom
Problem is in latest stable Spring versions also.

**Comment by NikitaZamalyutdinov** [comment]
Hi, guys, I've not tested, but it's [possible workaround ](https://stackoverflow.com/questions/38596474/is-saaj-compatible-with-mtom-xop)

**Comment by snicoll** [comment]
It's been a long time and we're now reviewing opened issues. Unfortunately, the sample in the original description works for me.

Is anyone watching willing to contribute a sample that demonstrates the problem against a supported version?

**Comment by mpeterka** [comment]
I have just updated project to the latest spring project versions.

You can use project https://github.com/mpeterka/spring-ws-mtom 
`cz.datalite.spring.mtom.client.WebServiceClientTest#testMarshallMtom`
, there just change "@Test(expected = org.springframework.oxm.MarshallingFailureException.class)" to "@Test" and you will get 

```

org.springframework.oxm.MarshallingFailureException: JAXB marshalling exception

	at org.springframework.oxm.jaxb.Jaxb2Marshaller.convertJaxbException(Jaxb2Marshaller.java:978)
	at org.springframework.oxm.jaxb.Jaxb2Marshaller.marshal(Jaxb2Marshaller.java:738)
	at org.springframework.ws.support.MarshallingUtils.marshal(MarshallingUtils.java:82)
	at org.springframework.ws.client.core.WebServiceTemplate$2.doWithMessage(WebServiceTemplate.java:431)
	at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:612)
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:575)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:422)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:416)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:406)
	at cz.datalite.spring.mtom.client.WebServiceClient.sendMarshal(WebServiceClient.java:36)
	at cz.datalite.spring.mtom.client.WebServiceClientTest.testMarshallMtom(WebServiceClientTest.java:57)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:76)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: jakarta.xml.bind.MarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-type.3.1.2: Element 'ns2:content' is a simple type, so it must have no element information item [children].]
	at org.glassfish.jaxb.runtime.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:268)
	at org.glassfish.jaxb.runtime.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:197)
	at org.springframework.oxm.jaxb.Jaxb2Marshaller.marshal(Jaxb2Marshaller.java:734)
	... 42 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-type.3.1.2: Element 'ns2:content' is a simple type, so it must have no element information item [children].
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:512)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3596)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidType(XMLSchemaValidator.java:3423)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processElementContent(XMLSchemaValidator.java:3343)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleEndElement(XMLSchemaValidator.java:2373)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:944)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.endElement(ValidatorHandlerImpl.java:585)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:558)
	at org.glassfish.jaxb.runtime.v2.runtime.output.SAXOutput.endTag(SAXOutput.java:105)
	at org.glassfish.jaxb.runtime.v2.runtime.output.XmlOutputAbstractImpl.endTag(XmlOutputAbstractImpl.java:105)
	at org.glassfish.jaxb.runtime.v2.runtime.output.ForkXmlOutput.endTag(ForkXmlOutput.java:59)
	at org.glassfish.jaxb.runtime.v2.runtime.output.MTOMXmlOutput.endTag(MTOMXmlOutput.java:85)
	at org.glassfish.jaxb.runtime.v2.runtime.XMLSerializer.leafElement(XMLSerializer.java:321)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl$PcdataImpl.writeLeafElement(RuntimeBuiltinLeafInfoImpl.java:151)
	at org.glassfish.jaxb.runtime.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.writeLeafElement(TransducedAccessor.java:224)
	at org.glassfish.jaxb.runtime.v2.runtime.property.SingleElementLeafProperty.serializeBody(SingleElementLeafProperty.java:94)
	at org.glassfish.jaxb.runtime.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:334)
	at org.glassfish.jaxb.runtime.v2.runtime.XMLSerializer.childAsSoleContent(XMLSerializer.java:556)
	at org.glassfish.jaxb.runtime.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:314)
	at org.glassfish.jaxb.runtime.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:456)
	at org.glassfish.jaxb.runtime.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:265)
	... 44 more
```
exception.

**Comment by snicoll** [comment]
> just change @Test(expected = org.springframework.oxm.MarshallingFailureException.class) to @TestBoost 

Ah, I see. Thanks for following-up. FWIW I would make that the default behavior so that the sample fails by default.

**Comment by arimu1** [comment]
Opened a fix in Spring Framework (where `Jaxb2Marshaller` lives): https://github.com/spring-projects/spring-framework/pull/37120

When both `mtomEnabled` and `schemas` are set, marshalling now validates the logical (non-XOP) infoset first, then MTOM-encodes without schema so `xop:Include` children no longer trigger `cvc-type.3.1.2`.

**Comment by snicoll** [comment]
Thanks @mpeterka for the updated repro. The root cause is in Jaxb2Marshaller (spring-oxm): when mtomEnabled and a schema are both set, validation runs against the XOP-encoded stream instead of the logical infoset, so xop:Include children trip schema validation. This isn't a spring-ws issue as such, and a fix has been proposed upstream in spring-projects/spring-framework#37120 (thanks @arimu1).

Closing this here and tracking via that PR; it'll be considered resolved once it lands in Spring Framework.
