### ISSUE TITLE
TransformerFactoryUtils introduced in release 3.0.6 sets default properties that conflict with other TransformerFactory implementations [SWS-1054]

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-ws#1120]
**[Geert Graat](https://jira.spring.io/secure/ViewProfile.jspa?name=ggraat)** opened **[SWS-1054](https://jira.spring.io/browse/SWS-1054?redirect=false)** and commented

We recently upgraded to Spring WS 3.0.6. In this release, a new class is introduced, `TransformerFactoryUtils` (https://github.com/spring-projects/spring-ws/commit/1f05307d61d525ed74a7d6d70a2a3b132948cdfc), which before instantiating a `TransformerFactory` sets some defaults. 

The problem we have with this is that we do not use the default `TransformerFactory` implementation, but instead rely on the [Saxon-HE](http://saxon.sourceforge.net/#F9.9HE) library. When this `TransformerFactory` is instantiated, setting the defaults lead to an exception:

 

```java
Caused by: java.lang.IllegalArgumentException: Unrecognized configuration feature: http://javax.xml.XMLConstants/property/accessExternalDTDCaused by: java.lang.IllegalArgumentException: Unrecognized configuration feature: http://javax.xml.XMLConstants/property/accessExternalDTD at deployment.runtime.war//net.sf.saxon.Configuration.setConfigurationProperty(Configuration.java:4408) at deployment.runtime.war//net.sf.saxon.jaxp.SaxonTransformerFactory.setAttribute(SaxonTransformerFactory.java:311) at deployment.runtime.war//org.springframework.xml.transform.TransformerFactoryUtils.defaultSettings(TransformerFactoryUtils.java:53) at deployment.runtime.war//org.springframework.xml.transform.TransformerFactoryUtils.newInstance(TransformerFactoryUtils.java:32)
```

This prevents our application from starting up.

 

---

**Affects:** 3.0.6

**Comment by gregturn** [comment]
https://github.com/spring-projects/spring-ws/milestone/68?closed=1 was release February 2019.
