### ISSUE TITLE
Build failure on spring-xml

### ISSUE THREAD

**Issue by onionpsy** [spring-projects/spring-ws#1258]
Hello.

I get a build failure with `./mvnw clean package` because one test is failing in the `spring-xml` module:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.049 s <<< FAILURE! - in org.springframework.xml.transform.TransformerHelperTest
[ERROR] defaultTransformerFactory  Time elapsed: 0.049 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.springframework.xml.transform.TransformerHelperTest.setUp(TransformerHelperTest.java:42)
Caused by: org.easymock.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @3b2c72c2
	at org.springframework.xml.transform.TransformerHelperTest.setUp(TransformerHelperTest.java:42)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @3b2c72c2
	at org.springframework.xml.transform.TransformerHelperTest.setUp(TransformerHelperTest.java:42)
	
(...)
[ERROR] Errors: 
[ERROR]   TransformerHelperTest.setUp:42 » ExceptionInInitializer
[INFO] 
[ERROR] Tests run: 172, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Spring Web Services ................................ SUCCESS [  0.078 s]
[INFO] spring-xml ......................................... FAILURE [  4.358 s]
[INFO] spring-ws-core ..................................... SKIPPED
[INFO] spring-ws-security ................................. SKIPPED
[INFO] spring-ws-support .................................. SKIPPED
[INFO] spring-ws-test ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
```

My env:
```
openjdk 17.0.4 2022-07-19
OpenJDK Runtime Environment (build 17.0.4+8)
OpenJDK 64-Bit Server VM (build 17.0.4+8, mixed mode)
```

**Comment by gregturn** [comment]
If you're building the `main` branch of Spring WS on Java 17, you need to enable the `java11` profile. It pulls in dependencies no longer found inside the JDK and additionally adds the necessary "opens".

**Comment by onionpsy** [comment]
Thanks! Maybe it might be a good idea to add this information to the readme. I'm closing the issue.
