### ISSUE TITLE
GraalVM Native Image support

### ISSUE THREAD

**Issue by naihil** [spring-projects/spring-ws#1329]
This is not a bug report, only my experiments to build spring-ws in native image.
I have a simple project that uses WebServiceTemplate to send/receive SOAP messages.
It compiles fine but there were several runtime exceptions.
To resolve them I need following files in META-INF/native-image:
1. reflect-config.json:
```
[
  {
    "name" : "com.sun.org.apache.xpath.internal.functions.FuncNormalizeSpace",
    "allDeclaredConstructors": true
  },
  {
    "name" : "org.springframework.ws.soap.saaj.SaajSoapMessageFactory",
    "allDeclaredConstructors": true
  },
  {
    "name" : "org.springframework.ws.transport.http.HttpUrlConnectionMessageSender",
    "allDeclaredConstructors": true
  },
  {
    "name" : "org.springframework.ws.soap.client.core.SoapFaultMessageResolver",
    "allDeclaredConstructors": true
  },
  {
    "name" : "org.springframework.ws.soap.server.endpoint.adapter.method.SoapMethodArgumentResolver",
    "allDeclaredConstructors": true
  },
  {
    "name" : "org.springframework.ws.soap.server.endpoint.adapter.method.SoapHeaderElementMethodArgumentResolver",
    "allDeclaredConstructors": true
  }
]

```

2. resource-config.json:
```
{
  "resources": {
    "includes": [
      {
        "pattern": "\\Qorg\/springframework\/ws\/transport\/http\/MessageDispatcherServlet.properties\\E"
      },
      {
        "pattern": "\\Qorg\/springframework\/ws\/client\/core\/WebServiceTemplate.properties\\E"
      },
      {
        "pattern": "\\Qorg\/springframework\/ws\/server\/MessageDispatcher.properties\\E"
      },
      {
        "pattern": "\\Qorg\/springframework\/ws\/soap\/server\/SoapMessageDispatcher.properties\\E"
      }
    ]
  }
}

```

Maybe this helps someone to submit official support to spring-ws.

**Comment by ksilz** [comment]
My Spring Boot 3.0.2 project with Spring Web Services 4.0.1 does **not** build with GraalVM. I get this error:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'annotationActionEndpointMapping': Instantiation of supplied bean failed
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1236) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[cat-importer-print:6.0.4]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:261) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:761) ~[cat-importer-print:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:568) ~[cat-importer-print:6.0.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[cat-importer-print:3.0.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[cat-importer-print:3.0.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[cat-importer-print:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[cat-importer-print:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[cat-importer-print:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[cat-importer-print:3.0.2]
	at com.gb.cat.importerprint.ImporterPrintApplication.main(ImporterPrintApplication.java:30) ~[cat-importer-print:na]
Caused by: org.springframework.xml.xpath.XPathParseException: Could not compile [normalize-space(wsa:To)] to a XPathExpression: javax.xml.transform.TransformerException: com.sun.org.apache.xpath.internal.functions.FuncNormalizeSpace.<init>()
	at org.springframework.xml.xpath.Jaxp13XPathExpressionFactory.createXPathExpression(Jaxp13XPathExpressionFactory.java:82) ~[na:na]
	at org.springframework.xml.xpath.XPathExpressionFactory.createXPathExpression(XPathExpressionFactory.java:72) ~[na:na]
	at org.springframework.ws.soap.addressing.version.AbstractAddressingVersion.createNormalizedExpression(AbstractAddressingVersion.java:115) ~[cat-importer-print:na]
	at org.springframework.ws.soap.addressing.version.AbstractAddressingVersion.<init>(AbstractAddressingVersion.java:89) ~[cat-importer-print:na]
	at org.springframework.ws.soap.addressing.version.Addressing200408.<init>(Addressing200408.java:37) ~[na:na]
	at org.springframework.ws.soap.addressing.server.AbstractAddressingEndpointMapping.initDefaultStrategies(AbstractAddressingEndpointMapping.java:113) ~[cat-importer-print:na]
	at org.springframework.ws.soap.addressing.server.AbstractAddressingEndpointMapping.<init>(AbstractAddressingEndpointMapping.java:103) ~[cat-importer-print:na]
	at org.springframework.ws.soap.addressing.server.AbstractActionEndpointMapping.<init>(AbstractActionEndpointMapping.java:38) ~[cat-importer-print:na]
	at org.springframework.ws.soap.addressing.server.AbstractActionMethodEndpointMapping.<init>(AbstractActionMethodEndpointMapping.java:33) ~[cat-importer-print:na]
	at org.springframework.ws.soap.addressing.server.AnnotationActionEndpointMapping.<init>(AnnotationActionEndpointMapping.java:61) ~[cat-importer-print:na]
	at org.springframework.ws.config.annotation.WsConfigurationSupport.annotationActionEndpointMapping(WsConfigurationSupport.java:109) ~[cat-importer-print:na]
	at org.springframework.ws.config.annotation.DelegatingWsConfiguration$$SpringCGLIB$$0.CGLIB$annotationActionEndpointMapping$6(<generated>) ~[cat-importer-print:na]
	at org.springframework.ws.config.annotation.DelegatingWsConfiguration$$SpringCGLIB$$1.invoke(<generated>) ~[cat-importer-print:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[cat-importer-print:6.0.4]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[na:na]
	at org.springframework.ws.config.annotation.DelegatingWsConfiguration$$SpringCGLIB$$0.annotationActionEndpointMapping(<generated>) ~[cat-importer-print:na]
	at org.springframework.ws.config.annotation.WsConfigurationSupport__BeanDefinitions.lambda$getAnnotationActionEndpointMappingInstanceSupplier$2(WsConfigurationSupport__BeanDefinitions.java:62) ~[na:na]
	at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:63) ~[cat-importer-print:6.0.4]
	at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:51) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$withGenerator$0(BeanInstanceSupplier.java:173) ~[na:na]
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[cat-importer-print:6.0.4]
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:208) ~[na:na]
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:59) ~[cat-importer-print:6.0.4]
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:47) ~[cat-importer-print:6.0.4]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:220) ~[na:na]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:208) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225) ~[cat-importer-print:6.0.4]
	... 18 common frames omitted
Caused by: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: com.sun.org.apache.xpath.internal.functions.FuncNormalizeSpace.<init>()
	at java.xml@17.0.5/com.sun.org.apache.xpath.internal.jaxp.XPathImpl.compile(XPathImpl.java:174) ~[na:na]
	at org.springframework.xml.xpath.Jaxp13XPathExpressionFactory.createXPathExpression(Jaxp13XPathExpressionFactory.java:78) ~[na:na]
	... 45 common frames omitted
Caused by: javax.xml.transform.TransformerException: com.sun.org.apache.xpath.internal.functions.FuncNormalizeSpace.<init>()
	at java.xml@17.0.5/com.sun.org.apache.xpath.internal.compiler.FunctionTable.getFunction(FunctionTable.java:353) ~[na:na]
	at java.xml@17.0.5/com.sun.org.apache.xpath.internal.compiler.Compiler.compileFunction(Compiler.java:1060) ~[na:na]
	at java.xml@17.0.5/com.sun.org.apache.xpath.internal.compiler.Compiler.compile(Compiler.java:204) ~[na:na]
	at java.xml@17.0.5/com.sun.org.apache.xpath.internal.compiler.Compiler.compile(Compiler.java:152) ~[na:na]
	at java.xml@17.0.5/com.sun.org.apache.xpath.internal.compiler.Compiler.compileExpression(Compiler.java:126) ~[na:na]
	at java.xml@17.0.5/com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:217) ~[na:na]
	at java.xml@17.0.5/com.sun.org.apache.xpath.internal.jaxp.XPathImpl.compile(XPathImpl.java:166) ~[na:na]
	... 46 common frames omitted
```

**Comment by ksilz** [comment]
@naihil Thank you! Worked like a charm for me!

How do find out this stuff?

**Comment by plebcity** [comment]
This is one of the reasons why we stopped using native image. There are too many libraries even from Spring themselves that don't support it fully yet which requires a lot of maintenance work for us.

**Comment by snicoll** [comment]
We can provide some hints from our own use but I wonder if that would be enough to make it compliant.
