### ISSUE TITLE
Using SOAP security in docker

### ISSUE THREAD

**Issue by giovannitro96** [spring-projects/spring-ws#1340]
When using SOAP security in a docker container doesn't work if the logging level of
`logging.org.springframework.ws `
is different from DEBUG, the returned error is:
```
java.lang.IllegalArgumentException: Cannot find SOAP wrapper for element [xenc:EncryptedData: null]
2023-03-14 09:01:51     at com.sun.xml.messaging.saaj.soap.SOAPDocumentImpl.find(SOAPDocumentImpl.java:590) ~[saaj-impl-1.5.3.jar!/:1.5.3]
2023-03-14 09:01:51     at com.sun.xml.messaging.saaj.soap.SOAPDocumentImpl.find(SOAPDocumentImpl.java:578) ~[saaj-impl-1.5.3.jar!/:1.5.3]
2023-03-14 09:01:51     at com.sun.xml.messaging.saaj.soap.impl.ElementImpl.getFirstChildElement(ElementImpl.java:660) ~[saaj-impl-1.5.3.jar!/:1.5.3]
2023-03-14 09:01:51     at com.sun.xml.messaging.saaj.soap.impl.BodyImpl.getPayloadQName(BodyImpl.java:439) ~[saaj-impl-1.5.3.jar!/:1.5.3]
2023-03-14 09:01:51     at com.sun.xml.messaging.saaj.soap.impl.BodyImpl.hasFault(BodyImpl.java:151) ~[saaj-impl-1.5.3.jar!/:1.5.3]
2023-03-14 09:01:51     at org.springframework.ws.soap.saaj.SaajSoapBody.hasFault(SaajSoapBody.java:55) ~[spring-ws-core-3.1.4.jar!/:na]
2023-03-14 09:01:51     at org.springframework.ws.soap.AbstractSoapMessage.hasFault(AbstractSoapMessage.java:62) ~[spring-ws-core-3.1.4.jar!/:na]
2023-03-14 09:01:51     at org.springframework.ws.soap.AbstractSoapMessage.getFaultCode(AbstractSoapMessage.java:68) ~[spring-ws-core-3.1.4.jar!/:na]
2023-03-14 09:01:51     at org.springframework.ws.transport.support.WebServiceMessageReceiverObjectSupport.handleConnection(WebServiceMessageReceiverObjectSupport.java:94) ~[spring-ws-core-3.1.4.jar!/:na]
```

Used dependency is last one, 4.0.2.

**Comment by pdotsenko** [comment]
I get this exact error regardless of spring-ws log level.  Using spring-ws 4.0.10.  Tried saaj-impl 2.0.1 and 3.0.3, same error.

**Comment by corneil** [comment]
@kommpn, @pdotsenko Can you create a small reproducer project to illustrate the issue.
