### ISSUE TITLE
Creating MockWebServiceServer with application context fails with two different web service templates. [SWS-915]

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-ws#990]
**[Shiv Veeram](https://jira.spring.io/secure/ViewProfile.jspa?name=shivaveeram)** opened **[SWS-915](https://jira.spring.io/browse/SWS-915?redirect=false)** and commented

Looks like this is working as design, but how do I test two different web service clients defined in the same application context.

Exception:

Creating mockwebserviceserver for one of the client with application context fails as it finds two web service template to deal with. Is there a way to feed the web service template needed for this client at that time ? Please advise.

Let me know if you have any queries.

org.springframework.beans.factory.BeanInitializationException: Could not find exactly 1 WebServiceTemplate in application context
at org.springframework.ws.test.support.MockStrategiesHelper.getStrategy(MockStrategiesHelper.java:84)
at org.springframework.ws.test.client.MockWebServiceServer.createServer(MockWebServiceServer.java:142)

---
No further details from [SWS-915](https://jira.spring.io/browse/SWS-915?redirect=false)

**Comment by snicoll** [comment]
Apologizes for the delay in responding. `MockWebServiceServer` need to identify the client to mock. Rather than using `MockWebServiceServer.createServer` with an application context, you can use it with the template that you want to use.

> Is there a way to feed the web service template needed for this client at that time ?

Yes. There is a `MockWebServiceServer.createServer` that takes a `WebServiceTemplate`.
